PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS `expenditures` (
  `id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `amount`	INTEGER NOT NULL,
  `date` DATETIME NOT NULL,
  'category_id' INTEGER,

  FOREIGN KEY(`category_id`) REFERENCES `categories`(`id`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `categories` (
  `id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `name`	TEXT NOT NULL UNIQUE
);
